uw-it-edm/content-services-ui

- .angular-cli.json
- .travis.yml
- src/environments/environment.travis.ts
use the `Build stages` feature of travis to run all tests ( and a prod build to make sure we can deploy) in parallel
> run test, e2e tests and prod build in parallel

- src/.htaccess
- src/app/app.module.ts
- src/app/routing/routing.module.ts
- src/environments/environment.travis.ts
- src/environments/environment.ts
- src/index.html
I stopped using the `APP_INITIALIZER`.
Ansible is now responsible to set the correct base href using `yarn build -- --prod --base-href {{base_href}}`
> fix base href issue

- e2e/mocks/profile-api/demo.json
- src/app/search/search-daterange-picker/search-daterange-picker.component.html
- src/app/search/search-daterange-picker/search-daterange-picker.component.spec.ts
- src/app/search/search-daterange-picker/search-daterange-picker.component.ts
* Remove daterange-picker cancel, clear, apply buttons -- apply on select
* Known bug, when clearing the daterange filter, the daterange-picker field does not clear -- we are planning to replace this component with the angular material2 picker ( https://github.com/angular/material2/issues/4763 ) when it is released
> Remove daterange-picker cancel, clear, apply buttons

- e2e/create/create.local-spec.ts
- e2e/edit/edit.local-spec.ts
- e2e/search/display-search.local-spec.ts
- src/app/content/content-metadata/content-metadata.component.html
Turn off accessibility check for Search Display All page because it is inconsistent with iframes.
Rearrange div/ul because div is not allowed directly under ul.
> Enable automated accessibility checks for Create and Edit pages.

- src/app/shared/providers/dataapivalue.service.ts
- add sortby label to data-api listByType & listByTypeAndParent
> CAB-3773: Exec Office data-api is not sorting alphabetically

- src/app/content/create-page/create-page.component.spec.ts
- src/app/content/edit-page/edit-page.component.spec.ts
- src/app/routing/shared/config-resolver.service.spec.ts
- src/app/search/display-search-page/display-search-page.component.spec.ts
- src/app/search/search-page/search-page.component.spec.ts
- src/app/shared/widgets/header/header.component.spec.ts
- src/app/user/shared/user.service.spec.ts
This pull request deals with errors of the form:
`No component factory found for NotificationComponent`
As far as I can tell, the underlying issue, is that whenever a component calls NotificationService.error(), the service internally calls:
`this.snackBar.openFromComponent(NotificationComponent, config);`
Notice that the NotificationComponent class is passed as a parameter. When running unit tests, the call to configureTestingModule may provide the required NotificationService type, but does not add the NotificationComponent to the list of declarations. Which makes _some_ sense because the unit tests are not expecting the component under test to call NotificationService.error().
The culprit seems to be the HeaderComponent that uses the UserService (which internally uses the …
> CAB-3844: Fixes intermittent unit test failures

- package.json
- yarn.lock
This works around a change in transitive dependency (semver package) that was updated to a version that no longer supports Node v8.
Created CAB-3856 to revert the lock if we find it necessary after we move to a more recent Node version.
Commit that introduced the change: 103e20b1891d05ce86d8c49ed7f84407647d8b70 build(deps-dev): bump rxjs-tslint-rules from 4.27.1 to 4.28.0
rxjs-tslint-rules updates the version of semver to ^7.0.0 and starting from that version, semver no longer supports Node8. See:
- https://github.com/cartant/rxjs-tslint-rules/compare/v4.27.1...v4.28.0
- https://github.com/npm/node-semver/compare/v6.3.0...v7.1.1
> Locks rxjs-tslint-rules package to 4.27.1

- src/app/shared/widgets/options-input/options-input.component.html
- src/app/shared/widgets/options-input/options-input.component.spec.ts
Fixes CAB-3803 (Selected value in drop downs not read by screen reader).
This change ONLY addresses the screen reader announcing the currently selected value of the dropdown. Interacting with the mat-select component with a screen reader is still a problem due to https://github.com/angular/components/issues/11083.
> Adds an aria-label to the mat-select component so that it displays the currently selected value when the select box is displayed.

- src/app/shared/widgets/options-input/options-input.component.html
- src/app/shared/widgets/options-input/options-input.component.spec.ts
Fixes CAB-3803.
According to WC3, the aria-label attribute is meant to read the label of the listbox. With commit 35bae7ff1459147ad94affa028119517fc1b6b71, the aria-label was changed to read the selected option's value, which is not what this attribute is meant to be used for. This commit changes the aria-label to first display the standard label name, and then appends the selected option value. Even though it is not standard to use this attribute to read the selected value, it is meant to mitigate the problem with mat-select where the selected option is not read at all.
> Prepends the label of the select component as part of the aria-label.

- .gitignore
- README.md
- angular.json
- package.json
- src/environments/environment.proxy.template.ts
- src/environments/local-proxy.conf.template.json
- src/environments/replace-vars.mjs
High level changes:
- There is a script that can injects values from environment variables into configuration files.
- When 'yarn start-localproxy' is run an environment.proxy.ts file is created that has all paths to API's marked as relative (it also has your netId from environment variable).
- A 'local-proxy.conf.json' file is also created that maps all the relative API's to a localhost address with the port taken from environment variables. These are marked with 'changeOrigin=true' to bypass CORS.
> Adds ability to start dev server with a proxy setup for each service.

- README.md
- package.json
> Updates to allow running tunneling server with Node 9 or above.

- src/app/core/shared/model/field.ts
- src/app/search/search-results/search-results.component.css
- src/app/search/search-results/search-results.component.html
- src/app/search/search-results/search-results.component.ts
- src/app/shared/widgets/display-field/display-field.component.css
- src/app/shared/widgets/display-field/display-field.component.html
- src/app/shared/widgets/display-field/display-field.component.spec.ts
- src/app/shared/widgets/display-field/display-field.component.ts
Fixes CAB-3902.
Summary: Row cell should always be aligned to its header cell. If it is left-aligned, left-most character of row cell should align to the left-most character of header cell. If it is right-aligned, right-most character of row cell should align to the right-most character of header cell.
Left alignment is automatically done by mat-table. Right alignment is done by matching the right-padding of the row cell and the header cell (taking into account the possibility of the up/down sorting arrow). The paddings of content inside the flex box are:
|   | Flex   | Left Padding  | Right Padding  |
|------|------|------|------|
| Header/Left/Sortable | Default | 0 | 18px (automatically mat-table up/down arrow) |
| Header/Left/Non-Sortable | Default |    0  |   inherit (automatically …
> Adds default left or right justification to cells of search page depending on the displayType.

- package.json
- yarn.lock
- upgrade karma to version 5+
- This does not completely resolve the issue other dependencies still require the older version of the library
> Content-services-ui: dependency security alerts - April 2020

- e2e/create/create.local-spec.ts
- e2e/create/create.po.ts
- e2e/mocks/profile-api/demo.json
- e2e/mocks/profile-api/demo2.json
- e2e/mocks/profile-api/demo3.json
- e2e/mocks/profile-api/demo4.json
- src/app/content/content-object-list/content-object-list.component.ts
- src/app/content/create-page/create-page.component.html
- src/app/content/create-page/create-page.component.ts
- src/app/core/shared/model/content-page-config.ts
Features from CAB-3985 not included in PR:
- Clicking Save will bring user back to Search page -> The keyboard focus should be on the searchbox
- Clicking "Save and Upload Another" will remain on the Upload page -> The keyboard focus should be on the Browse file button.
> CAB-3985: Change "Upload Another" checkbox to "Save and Upload Another" button.

- package.json
The `post-install` script was added as a patch to a bug in Protractor 5. Looks like version 7 took care of it.
> Revert patch for Protractor 5

- src/app/content/bulk-edit-page/bulk-edit-page.component.spec.ts
- src/app/content/bulk-edit-page/bulk-edit-page.component.ts
Even though the unit test looked ok, when I actually tried it live the snackbar shows [Object object] for some of the errors.
> BulkEditPageComponent: Fixes the error message that is displayed in the SnackBar.

- src/app/search/search-page/search-page.component.html
- src/app/search/search-page/search-page.component.spec.ts
- src/app/search/search-page/search-page.component.ts
Long term solution is tracked by https://jira.cac.washington.edu/browse/CAB-4078
> Bulk Update: Caps the maximum number of documents to select for bulk edit to 50.

- src/app/content/create-page/create-page.component.html
- src/app/content/edit-page/edit-page.component.html
type="button" was introduced as part of f97a90f81a5de0b564586c0ec6a351dacc3775a7, but now I realized that some buttons had a [type] binding.
> CAB-4082: Adds default button type if none is specified in config.

- src/app/content/create-page/create-page.component.html
The focus directive is here: https://github.com/uw-it-edm/content-services-ui/blob/develop/src/app/shared/directives/focus/focus.directive.ts
When adding that directive to two elements on the page, this checked error may be thrown, the create page had two FileUploadComponents that used it to try to set auto-focus.
> CAB-4069: Fixes error 'ExpressionChangedAfterItHasBeenCheckedError' that is thrown when two components in the same page use the FocusDirective.

- e2e/mocks/content-api/item.json
- e2e/mocks/profile-api/demo.json
- src/app/content/bulk-edit-page/bulk-edit-page.component.spec.ts
- src/app/content/bulk-edit-page/bulk-edit-page.component.ts
- src/app/content/content-metadata/content-metadata.component.html
- src/app/content/content-metadata/content-metadata.component.spec.ts
- src/app/content/content-metadata/content-metadata.component.ts
- src/app/shared/providers/fieldoption.service.ts
- src/app/shared/widgets/options-autocomplete/options-autocomplete.component.html
- src/app/shared/widgets/options-autocomplete/options-autocomplete.component.spec.ts
- src/app/shared/widgets/options-autocomplete/options-autocomplete.component.ts
Notes:
- Adapted from: https://material.angular.io/components/chips/examples
- There are a lot of code style changes, this is because the husky pre-commit was not running on my system before (!!). Once I fixed that, the coding style changes kicked in.
- E2E tests will be done on a separate PR.
> CAB-3812: Allow multiple Data-API backed values to be selected in UUI.

- e2e/mocks/profile-api/demo.json
- src/app/content/content-metadata/content-metadata.component.html
- src/app/content/content-metadata/content-metadata.component.spec.ts
- src/app/shared/shared.module.ts
- src/app/shared/widgets/options-autocomplete/options-autocomplete.component.base.ts
- src/app/shared/widgets/options-autocomplete/options-autocomplete.component.css
- src/app/shared/widgets/options-autocomplete/options-autocomplete.component.html
- src/app/shared/widgets/options-autocomplete/options-autocomplete.component.spec.ts
- src/app/shared/widgets/options-autocomplete/options-autocomplete.component.ts
- src/app/shared/widgets/options-multiselect/options-multiselect.component.css
- src/app/shared/widgets/options-multiselect/options-multiselect.component.html
- src/app/shared/widgets/options-multiselect/options-multiselect.component.spec.ts
- src/app/shared/widgets/options-multiselect/options-multiselect.component.ts
The primary motivation of this PR is forward maintainability and it includes no feature work.
My initial intuition was that the single and multi select UI experience was similar enough where I would treat multiSelect as an config option. As the code base has grown, the differences between the two experiences have become greater and are primarily handled by if/else branches. I believe that keeping them separate (while still sharing common code) will make future changes easier to handle.
In broad terms, this PR:
- Moves shareable code into base class (options-autocomplete.component.base.ts).
- It's two sub-classes are options-autocomplete.component.ts and options-multiselect.component.ts, the differences between the two components are kept in their own html and ts files.
These changes can …
> Refactors single and multi-select into 2 components.

- e2e/mocks/profile-api/demo.json
- e2e/mocks/search-api/search.json
- src/app/search/search-results/search-results.component.html
- src/app/shared/shared.module.ts
- src/app/shared/widgets/display-field/display-field.component.html
- src/app/shared/widgets/display-field/display-field.component.ts
- src/app/shared/widgets/list-field-display/list-field-display.component.css
- src/app/shared/widgets/list-field-display/list-field-display.component.html
- src/app/shared/widgets/list-field-display/list-field-display.component.spec.ts
- src/app/shared/widgets/list-field-display/list-field-display.component.ts
Notes:
- Same component can be used for data-api backed list as well as static lists.
- We can definitely change the UI going forward, but I feel this is decent enough for the first iteration.
- Only uses information from 'SourceModel', a subsequent PR will make a similar change for the 'DataApiValueDisplayComponent'.
> CAB-4044: Allow multiple Data-API backed values to be displayed in UUI search results.

- src/app/shared/widgets/data-api-display/data-api-value-display.component.spec.ts
- src/app/shared/widgets/data-api-display/data-api-value-display.component.ts
- src/app/shared/widgets/display-field/display-field.component.html
Notes:
- This component is also used by the facets-box component, and in that case it may need to query data-api to get the display value.
> DataApiValueDisplayComponent: Updates to use value directly from 'sourceModel' instead of calling data-api.

- src/app/core/shared/config.service.spec.ts
- src/app/core/shared/config.service.ts
- src/app/core/shared/model/field.ts
- src/app/core/shared/model/page-config.ts
The idea behind this feature is to be able to define the fields used for a profile once and re-use them for all pages. For EHS Radiation profile it will allow config to override just the one property that is different for the edit page:
```
fieldReferencesToDisplay: [
{ key: 'ReleaseDate', override: { disabled: true } },
{ key: 'DocumentType', override: { disabled: true } },
'Building',
'Floor'
],
```
> Adds ability to override properties when using field references.

- src/app/content/edit-page/edit-page.component.html
This change moves the button to be outside of the "view-wrapper", which keeps it below the preview pane even when in full screen.
> CAB-4092: UUI: Delete button not hidden on Document Preview Full Screen Mode

- .github/renovate.json
- Disables 'moment-timezone'. Latest error: https://travis-ci.org/github/uw-it-edm/content-services-ui/jobs/709767594.
- Enables auto-merging of some runtime 'dependendencies': lodash, rxjs and tslib (only for minor and patch updates).
> Updates renovate to allow auto-merging of some 'dependencies' and completely disable 'moment-timezone'.

- src/app/content/content-object-list/content-object-list.component.ts
Makes behavior similar to Bulk Edit Page. For more information see: https://jira.cac.washington.edu/browse/CAB-4081
> Edit Page: Only auto-dismiss snackbar when there are no errors to report after saving item.

- src/app/content/bulk-edit-page/bulk-edit-page.component.html
- src/app/content/bulk-edit-page/bulk-edit-page.component.spec.ts
- src/app/content/bulk-edit-page/bulk-edit-page.component.ts
- src/app/content/create-page/create-page.component.html
- src/app/content/create-page/create-page.component.ts
- src/app/content/edit-page/edit-page.component.html
- src/app/content/edit-page/edit-page.component.ts
- src/app/search/search-box/search-box.component.html
- src/app/search/search-box/search-box.component.ts
- src/app/search/search-page/search-page.component.ts
- src/app/shared/shared/auto-focus-navigation-state.ts
Summary of design:
- There is a shared interface that components can use to request auto-focus behavior to the navigation target.
- Pages that support auto-focus, can read the state and apply focus when requested by the navigation caller.
- SearchPageComponent applies auto-focus by placing it on the search box.
- SearchPageComponent also needs to deal with setting focus when moving out of bulk edit selection.
Not included:
- Unit tests and/or integration tests.
> CAB-4025: UUI: Focus should be on the search box when navigating to Search Page.

- e2e/browserUtils.ts
- e2e/search/search.local-spec.ts
- src/app/content/bulk-edit-page/bulk-edit-page.component.spec.ts
Test strategy:
Instead of verifying each individual navigation case, the primary goal is to verify that the search page puts focus on the search-box if the right navigation state is supplied by the source of navigation.
Additionally, verify the special case when exiting bulk edit mode the search page puts focus on the search-box.
Navigation sources can be tested via unit tests, and I updated the bulk-edit page unit test to check that the navigation state is passed.
> CAB-4024: Adds unit and integration tests for auto-focus on search box.

- .github/workflows/ci.yml
This is useful so that we can see which project triggered the alert when it comes.
> Updates github CI workflow to add a better message to slack notification.

- .github/workflows/ci.yml
GitHub action updates driver and chrome weekly, if the build updates the driver we need to update chrome. For more details see: https://github.com/actions/virtual-environments/issues/701
> Updates chrome on machine before running E2E tests.

- .github/workflows/ci.yml
See https://github.com/actions/virtual-environments/issues/675
> Removes the azure from apt-get sources list for E2E tests.

- src/app/app.component.css
- src/app/app.component.html
- src/app/app.component.spec.ts
- src/app/app.component.ts
- src/app/core/shared/model/config.ts
- src/app/routing/shared/config-resolver.service.spec.ts
- src/app/routing/shared/config-resolver.service.ts
- src/app/search/facets-box/facets-box.component.spec.ts
- src/app/shared/providers/application-state.service.ts
- src/app/shared/shared.module.ts
- src/app/shared/widgets/header/header.component.spec.ts
Summary:
This change follows the pattern described [here](https://angular.io/guide/component-interaction#parent-and-children-communicate-via-a-service) and adds a mechanism for components to communicate changes in state to the main app component. One of these states is the warning header message.
Notes:
- As always, the commit hook that runs 'prettier' re-formatted other lines in the files touched that are outside the scope of this change.
> CAB-4228: Adds a warning message to the UUI header set via config.

- e2e/mocks/content-api/item.json
- e2e/mocks/profile-api/demo6-currency.json
- e2e/mocks/profile-api/list.json
- src/app/content/content-metadata/content-metadata.component.html
- src/app/content/content-metadata/content-metadata.component.spec.ts
input type="number" rejects non-numerical entries. See https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/number.
A "$" prefix is also added to make it clear to user that the field represents a currency amount. See screen shot below.
> CAB-4325: Restricts input to number and adds $ prefix for displayType=currency fields.

- src/app/content/content-metadata/content-metadata.component.html
- src/app/content/content-metadata/content-metadata.component.spec.ts
- src/app/content/content-metadata/content-metadata.component.ts
Testing revealed that input with type="number" doesn't work well in all browsers. Switched the solution to use a regex validator instead. See screen shot below for experience.
> CAB-4325: Adds regex validator for number fields.
