uw-it-edm/content-services-ui

README.md

Added Travis build badges to the Readme

add Travis build badges

---

.angular-cli.json
.gitignore
src/.htaccess
src/app/app.module.ts
src/environments/environment.prod.ts
src/environments/environment.ts

git ignore env specific files
add htaccess file for html5 deep links
allow for configurable base href

Configure repo for dynamic base href and deploy on build servers

---

.angular-cli.json
src/app/model/page-config.ts
src/app/model/result-row.ts
src/app/model/search-model.ts
src/app/model/search-result.ts
src/app/pages/generic-page/generic-page.component.html
src/app/pages/generic-page/generic-page.component.spec.ts
src/app/pages/generic-page/generic-page.component.ts
src/app/pages/tenant/tenant.component.spec.ts
src/app/routing/routing.module.ts
src/app/services/config.service.ts
src/app/services/search.service.spec.ts
src/app/services/search.service.ts
src/app/user/user.service.ts
src/app/widgets/search-box/search-box.component.html
src/app/widgets/search-box/search-box.component.spec.ts
src/app/widgets/search-box/search-box.component.ts
src/app/widgets/search-results/search-results.component.html
src/app/widgets/search-results/search-results.component.spec.ts
src/app/widgets/search-results/search-results.component.ts
src/index.html

Also update the current karma test results to be more readable

CAB-2545 - first shot at handling search and search results

---

.travis.yml

will help see see why a build is failing in travis

add env variable to define job

---

e2e/app.e2e-spec.ts
e2e/app.po.ts
e2e/edit/edit.e2e-spec.ts
e2e/edit/edit.po.ts
e2e/search/search.e2e-spec.ts
e2e/search/search.po.ts

Adding basic protractor tests for Search and Edit pages

Add protractor tests for search and edit pages

---

src/app/content/content-metadata/content-metadata.component.html
src/app/search/search-page/search-page.component.ts

search service observable should be subscribed to in the search page, not in the underlying components

fixes CAB-2633 -

---

.travis.yml
e2e/app/app.po.ts
e2e/mocks/profile-api/list.json
package.json
protractor.conf.js
src/app/content/content-metadata/content-metadata.component.html
src/app/content/content-metadata/content-metadata.component.spec.ts
src/app/content/content-metadata/content-metadata.component.ts
src/app/content/content-object-list/content-object-list.component.spec.ts
src/app/content/content-pager/content-pager.component.spec.ts
src/app/content/content-toolbar/content-toolbar.component.spec.ts
src/app/content/content-view/content-view.component.spec.ts
src/app/content/edit-page/edit-page.component.spec.ts
src/app/core/shared/model/field.ts
src/app/core/shared/model/field/field-option.ts
src/app/shared/shared.module.ts
src/app/shared/widgets/file-upload/file-upload.component.spec.ts
src/app/shared/widgets/header/header.component.html
src/app/shared/widgets/options-input/options-input.component.html
src/app/shared/widgets/options-input/options-input.component.spec.ts
src/app/shared/widgets/options-input/options-input.component.ts
src/app/shared/widgets/timestamp-picker/timestamp-picker.component.spec.ts
src/environments/environment.travis.ts
yarn.lock

implement select-input

---

src/app/content/content-toolbar/content-toolbar.component.html
src/app/content/content-toolbar/content-toolbar.component.spec.ts
src/app/content/content-view/content-view.component.spec.ts
src/app/content/content-view/content-view.component.ts

fix errors in UI & unit test relating to changing the content-type from 'application/pdf' to 'pdf'

CAB-2883: UUI: Download and Zoom buttons not displayed on Previewer

---

src/app/shared/widgets/options-input/options-input.component.ts
src/app/shared/widgets/student-autocomplete/student-autocomplete.component.ts

Fixed focus in both option list as well as student-autocomplete

CAB-2753: Add focus indicator to select control

---

src/app/shared/providers/person.service.ts
src/app/shared/shared/model/person.ts
src/app/shared/widgets/person-autocomplete/person-autocomplete.component.spec.ts
src/app/shared/widgets/person-autocomplete/person-autocomplete.component.ts

Get registered name when preferred name doesn't exist. 
fix focus issue on input component

Fix bug discoverd while testing 

---

e2e/create/create.local-spec.ts
e2e/create/create.po.ts
e2e/edit/edit.local-spec.ts
e2e/edit/edit.po.ts
e2e/mocks/content-services-api-mocks.conf
e2e/mocks/data-api/person-query.json
e2e/mocks/data-api/person.json
e2e/mocks/profile-api/demo2.json
e2e/mocks/profile-api/list.json
e2e/search/search.local-spec.ts

Also adding a second demo profile to distinguish between student and employee auto complete configs.

add e2e tests for Employee auto complete.

---

e2e/mocks/profile-api/demo.json
e2e/mocks/search-api/search.json
src/app/search/facets-box/facets-box.component.html
src/app/search/facets-box/facets-box.component.spec.ts
src/app/search/facets-box/facets-box.component.ts
src/app/shared/directives/custom-text/custom-text-utilities.ts
src/app/shared/directives/custom-text/custom-text.directive.ts
src/app/shared/directives/custom-text/customized-text.ts

This was implemented using the custom text directive

CAB-3483 - Facets value text should be configurable

---

src/app/search/search-box/search-box.component.html

by reordering ngModel and ngModelChange  
see angular/angular#11234

Fix CAB-3528

---

src/app/search/search-box/search-box.component.html
src/app/search/search-box/search-box.component.spec.ts
src/app/search/search-box/search-box.component.ts
src/app/shared/shared/model/person.ts
src/app/shared/shared/model/student.ts

by encapsulating input in an internal field instead of using of using
straight SearchModel

Fix autocomplete issue

---

src/app/shared/providers/person.service.spec.ts
src/app/shared/providers/person.service.ts

CAB-3614 - Execute wildcard searches against data-api person endpoint

---

src/app/search/search-daterange-picker/search-daterange-picker.component.css

To allow displaying the whole placeholder

increase size of input box

---

.travis.yml
package.json

temp workaround until Protractor bug is fixed https://github.com/angular/protractor/issues/5289

patch Protractor 

---

src/app/search/facets-box/facets-box.component.css
src/app/search/facets-box/facets-box.component.html
src/app/search/search-results/search-results.component.html
src/app/search/search-results/search-results.component.ts

- id link should send to the right url
- you should be able to select text in the search result
- facet link should send to /null

Fixes CAB-3704

---

src/app/search/facets-box/facets-box.component.html

adding region per recommendation by accessibility office.

add region to facets

---

src/app/shared/widgets/header/header.component.css
src/app/shared/widgets/header/header.component.html

Removes the Logout button and makes the username element non-clickable.

---

e2e/create/create.local-spec.ts
e2e/create/create.po.ts
src/app/content/content-object-list/content-object-list.component.ts
src/app/content/create-page/create-page.component.html
src/app/content/create-page/create-page.component.ts
src/app/core/shared/model/content-page-config.ts

Create page should redirect to search page or clear form depending on 'Upload Another' checkbox status.

---

src/app/shared/widgets/display-field/display-field.component.html
src/app/shared/widgets/display-field/display-field.component.spec.ts

UUI Search page should display 4 digit year for Dates and DateTimes

---

.gitignore
e2e/create/create.local-spec.ts
e2e/mocks/content-services-api-mocks.conf

Adds e2e test to verify experience when user attempts to save a document but server returns error (Take #2)

---

src/app/shared/widgets/display-field/display-field.component.html
src/app/shared/widgets/display-field/display-field.component.spec.ts

This reverts commit 499cf7066098209db9f270a5beb8734489286c6c.

Revert "UUI Search page should display 4 digit year for Dates and DateTimes (#822)"

---

e2e/search/search.local-spec.ts
e2e/search/search.po.ts
src/app/search/search-results/search-results.component.ts
src/app/search/shared/search-utility.ts

Accessibility: UUI should notify column sorting in search results.

---

e2e/mocks/profile-api/demo3.json
e2e/mocks/search-api/search.json
src/app/core/shared/model/field.ts
src/app/shared/pipes/safe-currency.pipe.ts
src/app/shared/shared.module.ts
src/app/shared/widgets/display-field/display-field.component.html
src/app/shared/widgets/display-field/display-field.component.spec.ts
src/app/shared/widgets/display-field/display-field.component.ts

Adds a 'currency' display type that can be used to show field values as currency on the search page.

---

e2e/app/app.po.ts
e2e/mocks/content-services-api-mocks.conf
e2e/mocks/profile-api/demo2.json
e2e/mocks/profile-api/demo3.json
e2e/mocks/search-api/demo3.json
e2e/search/search.local-spec.ts
e2e/search/search.po.ts
src/app/search/search-page/search-page.component.ts
src/app/search/search-results/search-results.component.spec.ts
src/app/search/search-results/search-results.component.ts

Switching between UUI profiles fails to display initial search results.

---

src/app/shared/widgets/course-input/course-input.component.html
src/app/shared/widgets/course-input/course-input.component.spec.ts
src/app/shared/widgets/course-input/course-input.component.ts

Fixes so that dropdowns in course-input component announce selected values in screen reader.

---

src/app/shared/widgets/course-input/course-input.component.html
src/app/shared/widgets/course-input/course-input.component.spec.ts
src/app/shared/widgets/course-input/course-input.component.ts

Fix bug where Course dropdown was not properly clearing its aria-label when there was no course number selected.

---

README.md

I am not planning on adding more information to this readme.

Removes all TBD statements from README.md.

---

src/app/shared/widgets/options-input/options-input.component.html
src/app/shared/widgets/options-input/options-input.component.spec.ts
src/app/shared/widgets/options-input/options-input.component.ts

Accessibility: screen reader should announce the placeholder and label of dropdown field instead of value.

---

e2e/mocks/profile-api/demo4.json
e2e/mocks/profile-api/list.json
e2e/mocks/search-api/demo4.json
e2e/search/search.local-spec.ts
e2e/search/search.po.ts
src/app/search/search-page/search-page.component.css
src/app/search/search-page/search-page.component.html
src/app/search/search-page/search-page.component.spec.ts
src/app/search/search-page/search-page.component.ts
src/app/search/search-results/search-results.component.css
src/app/search/search-results/search-results.component.html

Adds ability to hide the filters so that the search table has more space to render.

---

src/app/content/content-view/content-view.component.html
src/app/shared/shared.module.ts

CAB-3801: Full screen mode does not limit keyboard navigation not in view
- trap focus within content-view when fullscreen

CAB-3801: Full screen mode does not limit keyboard navigation not in view

---

src/app/content/content-metadata/content-metadata.component.html
src/app/content/content-metadata/content-metadata.component.spec.ts
src/app/shared/providers/fieldoption.service.ts
src/app/shared/shared.module.ts
src/app/shared/widgets/options-autocomplete/options-autocomplete.component.html
src/app/shared/widgets/options-autocomplete/options-autocomplete.component.spec.ts
src/app/shared/widgets/options-autocomplete/options-autocomplete.component.ts
src/app/shared/widgets/options-input/options-input.component.spec.ts
src/app/shared/widgets/options-input/options-input.component.ts

As part of this change I tried to reuse as much code from the OptionsInputComponent which was abstracted into a new service.

CAB-3603: Adds a 'list-select' display type that uses an autocomplete component to allow users to filter the list of options.

---

e2e/mocks/profile-api/demo.json
src/app/core/shared/model/search-page-config.ts
src/app/search/search-page/search-page.component.css
src/app/search/search-page/search-page.component.html
src/app/search/search-page/search-page.component.spec.ts
src/app/search/search-page/search-page.component.ts
src/app/search/search-results/search-results.component.ts

There are a number of things that have not been decided by product owner. In particular:
- The title, instructions and button wording.
- Button positions.
For a full list of questions: https://docs.google.com/document/d/1sflNQiPC77B0u5AOmh7_siGZ9Ktbc5JM7zQo8rOrkrk/edit#heading=h.bx8zmk9x3mqe

CAB-4053 (part 3): Changes to SearchPageComponent to allow user to enter bulk edit mode and make selections.

---

e2e/mocks/profile-api/demo.json
src/app/content/bulk-edit-page/bulk-edit-page.component.css
src/app/content/bulk-edit-page/bulk-edit-page.component.html
src/app/content/bulk-edit-page/bulk-edit-page.component.spec.ts
src/app/content/bulk-edit-page/bulk-edit-page.component.ts
src/app/content/content.module.ts
src/app/content/shared/content.service.ts
src/app/content/shared/model/content-item.ts
src/app/core/shared/model/bulk-edit-page-config.ts
src/app/routing/routing.module.ts
src/app/search/search-page/search-page.component.ts
src/app/search/search.module.ts
src/app/shared/providers/data.service.ts

Note: the text, instructions and position of UI elements haven't been locked down yet.

CAB-4063: First iteration of bulk edit page that allows users to change fields and update multiple documents at same time.

---

e2e/browserUtils.ts
e2e/bulk-edit/bulk-edit.local-spec.ts
e2e/bulk-edit/bulk-edit.po.ts
e2e/edit/edit.foster.e2e-spec.ts
e2e/edit/edit.local-spec.ts
e2e/mocks/content-api/bulk-edit-success.json
e2e/mocks/content-services-api-mocks.conf
e2e/mocks/profile-api/demo.json
e2e/search/search-results.po.ts
e2e/search/search.local-spec.ts
e2e/search/search.po.ts
protractor.conf.local.js

There is only one E2E test here that verifies the whole user flow, other functionality is covered by unit tests.
Part of this PR is the beginnings of re-usable page objects: a page object for the SearchResultsComponent is created and used by several pages.

CAB-4075: Adds E2E test for Bulk Update feature.

---

src/app/content/bulk-edit-page/bulk-edit-page.component.html
src/app/content/create-page/create-page.component.html
src/app/content/edit-page/edit-page.component.html

See: http://w3c.github.io/html-reference/button.html

CAB-4082: Mark all buttons as type="button" to prevent forms from auto-submitting on ENTER.

---

e2e/bulk-edit/bulk-edit.local-spec.ts
e2e/bulk-edit/bulk-edit.po.ts
e2e/page-objects/content-metadata.po.ts
e2e/page-objects/search-results.po.ts
e2e/page-objects/select-field.po.ts
e2e/search/search.po.ts

This pull request takes another step closer to have re-usable PageObjects for components.

CAB-4073: E2E tests for cascading field validators for Bulk Update.

---

e2e/mocks/profile-api/demo.json
src/app/content/content-metadata/content-metadata.component.html
src/app/core/shared/model/field.ts
src/app/core/shared/model/filter-select-config.ts

This was a suggestion that came from code review.

CAB-3812: Adds configuration option to 'filter-select' display field type in favor of the 'multi-select' display type.

---

e2e/bulk-edit/bulk-edit.local-spec.ts
e2e/edit/edit.local-spec.ts
e2e/edit/edit.po.ts
e2e/mocks/profile-api/demo.json
e2e/page-objects/content-metadata.po.ts
e2e/page-objects/filter-select-field.po.ts
e2e/page-objects/select-field.po.ts

Sadly, this changes includes formatting updates from prettier. They get changed at commit time, so its hard to know what's gonna happen.

CAB-3812: Adds page objects and E2E test for filter select with multiple selection.

---

src/app/shared/widgets/options-autocomplete/options-autocomplete.component.ts

The first commit has purely formatting changes done by prettier, the second commit has the actual intended changes.

OptionsAutocompleteComponent: Adds comments to better describe the intent of some paths.

---

e2e/browserUtils.ts

Attempts to fix intermitent errors of the form: https://travis-ci.com/github/uw-it-edm/content-services-ui/jobs/446781539

E2E Test: Catches stale element errors when waiting for custom function.

---

src/app/content/content-view/content-view.component.html
src/app/content/content-view/content-view.component.spec.ts
src/app/content/content-view/content-view.component.ts
src/app/content/edit-page/edit-page.component.html
src/app/core/shared/model/content-page-config.ts
src/environments/environment.localmock-ie11.ts
src/environments/environment.localmock.ts
src/environments/environment.proxy.template.ts
src/environments/environment.travis.ts
src/environments/environment.ts

view and download persisted files from wcc directly  when wccUrl is set in the environment

CAB-4324 view and download persisted files from wcc directly 

---

src/app/content/content-toolbar/content-toolbar.component.html
src/app/content/content-toolbar/content-toolbar.component.spec.ts
src/app/content/content-toolbar/content-toolbar.component.ts
src/app/content/content-view/content-view.component.css
src/app/content/content-view/content-view.component.html

CAB-4346: UUI Zoom control in PDF Viewer does not display in iframe mode.
